#workers/api/wrangler.toml


name = "solostore-api"
main = "src/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SOLOSTORE_KV"
id = "f71e79c3fcc24c8c8516ddfbc5ed050d"
preview_id = "c0b19f5d88de4dce8ba7ffd706704c04"

[[r2_buckets]]
binding = "SOLOSTORE_R2"
bucket_name = "solostore-assets"
preview_bucket_name = "solostore-assets-preview"

[vars]
ENVIRONMENT = "development"

# Secrets:
#   SESSION_SECRET
#   STRIPE_SECRET_KEY
#   RESEND_API_KEY